[package]
name = "xtask"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
log = "0.4.0"
os-xtask-utils = {git = "https://github.com/listentodella/os-xtask-utils.git"}
pretty_env_logger = "0.5.0"


